In [ ]:
pip install -U scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.9/dist-packages (1.2.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn) (3.1.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from scikit-learn) (1.1.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.9/dist-packages (from scikit-learn) (1.22.4)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.9/dist-packages (from scikit-learn) (1.10.1)

In [ ]:
from sklearn.linear_model import Perceptron
x=[[0,0],[1,0],[0,1],[1,1]]
y=[0,1,1,1]
model=Perceptron()
model.fit(x,y)
model.score(x,y)

1.0

In [ ]:
x1=[[-0.5,-0.5],[10,-2],[-1,0.8],[3,5],[1,0.2],[-0.1,0.9]]
y1=model.predict(x1)
model.score(x1,y1)

1.0

In [ ]:
x2=[[0.5,0],[0,0.5]]
y2=model.predict(x2)
model.score(x2,y2)

1.0

In [ ]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [ ]:
iris=datasets.load_iris()
X=iris.data
y=iris.target
print(X[:5])
print(y[:5])
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)
sc=StandardScaler()
sc.fit(X_train)
X_train_std=sc.transform(X_train)
X_test_std=sc.transform(X_test)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]

In [ ]:
model=Perceptron(max_iter=40,eta0=0.1,random_state=0)
model.fit(X_train_std,y_train)
y_pred=model.predict(X_test_std)
print(y_pred)
print(y_test)
print('Độ chính xác của mô hình:',accuracy_score(y_test,y_pred))

[1 0 1 2 1 0 1 1 0 2 2 1 2 1 1 1 1 0 0 0 1 0 2 0 1 1 1 0 0 1 0 2 0 1 1 0 0
 2 1 2 0 0 1 1 1]
[1 0 1 2 2 0 1 1 0 2 2 2 2 1 2 2 1 0 0 0 2 0 2 0 1 1 1 0 0 1 0 2 0 1 1 0 0
 2 1 2 0 0 2 2 2]
Độ chính xác của mô hình: 0.8222222222222222

# Bai tap crab.csv

In [ ]:
import pandas as pd
url='crabs.csv'
data = pd.read_csv(url)
data.head()

  speies sex  index  fontallip  rearwidth  length  width  depth
0      B   M      1        8.1        6.7    16.1   19.0    7.0
1      B   M      2        8.8        7.7    18.1   20.8    7.4
2      B   M      3        9.2        7.8    19.0   22.4    7.7
3      B   M      4        9.6        7.9    20.1   23.1    8.2
4      B   M      5        9.8        8.0    20.3   23.0    8.2

In [ ]:
data.replace(to_replace=["B","F"],value=0)
data.replace(to_replace=["O","M"],value=1)

    speies sex  index  fontallip  rearwidth  length  width  depth
0        B   1      1        8.1        6.7    16.1   19.0    7.0
1        B   1      2        8.8        7.7    18.1   20.8    7.4
2        B   1      3        9.2        7.8    19.0   22.4    7.7
3        B   1      4        9.6        7.9    20.1   23.1    8.2
4        B   1      5        9.8        8.0    20.3   23.0    8.2
..     ...  ..    ...        ...        ...     ...    ...    ...
195      1   F     46       21.4       18.0    41.2   46.2   18.7
196      1   F     47       21.7       17.1    41.7   47.2   19.6
197      1   F     48       21.9       17.2    42.6   47.4   19.5
198      1   F     49       22.5       17.2    43.0   48.7   19.8
199      1   F     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]

In [ ]:
X = data.iloc[:,3:]
y = data.iloc[:,1]
X

     fontallip  rearwidth  length  width  depth
0          8.1        6.7    16.1   19.0    7.0
1          8.8        7.7    18.1   20.8    7.4
2          9.2        7.8    19.0   22.4    7.7
3          9.6        7.9    20.1   23.1    8.2
4          9.8        8.0    20.3   23.0    8.2
..         ...        ...     ...    ...    ...
195       21.4       18.0    41.2   46.2   18.7
196       21.7       17.1    41.7   47.2   19.6
197       21.9       17.2    42.6   47.4   19.5
198       22.5       17.2    43.0   48.7   19.8
199       23.1       20.2    46.2   52.5   21.1

[200 rows x 5 columns]

In [ ]:
from sklearn import datasets
from sklearn.linear_model import Perceptron 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train) 
X_test_std = sc.transform(X_test)

In [ ]:

model = Perceptron(max_iter = 1000, eta0 = 0.1, random_state = 0)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(y_pred[:10])
print(y_test[:10])
print("Do chinh xac mo hinh chua scale : ", accuracy_score(y_test, y_pred))

['F' 'F' 'F' 'F' 'F' 'F' 'F' 'M' 'F' 'F']
0      M
92     F
16     M
151    F
100    M
98     F
28     M
129    M
192    F
170    F
Name: sex, dtype: object
Do chinh xac mo hinh chua scale :  0.6833333333333333

In [ ]:
model = Perceptron(max_iter = 1000, eta0 = 0.1, random_state = 0)
# (so lan hoc, toc do hoc, ngau nhien=0)
model.fit(X_train_std, y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test[:10])
print("Do chinh xac mo hinh sau scale : ", accuracy_score(y_test, y_pred))

['F' 'F' 'M' 'F' 'F' 'F' 'M' 'M' 'F' 'F' 'F' 'F' 'M' 'F' 'F' 'M' 'F' 'F'
 'F' 'M' 'F' 'F' 'F' 'F' 'F' 'F' 'M' 'M' 'F' 'M' 'F' 'F' 'F' 'F' 'F' 'M'
 'M' 'M' 'F' 'M' 'F' 'M' 'M' 'M' 'M' 'M' 'M' 'F' 'F' 'M' 'F' 'F' 'M' 'F'
 'F' 'F' 'F' 'M' 'F' 'F']
0      M
92     F
16     M
151    F
100    M
98     F
28     M
129    M
192    F
170    F
Name: sex, dtype: object
Do chinh xac mo hinh sau scale :  0.8333333333333334

# Bai tap lung cancer example

In [ ]:
import pandas as pd
url_lcancer = 'lung_cancer_examples.csv'
lucancer = pd.read_csv(url_lcancer)
lucancer.head(10)

        Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0       John         Wick   35       3      5       4       1
1       John  Constantine   27      20      2       5       1
2     Camela     Anderson   30       0      5       2       0
3       Alex       Telles   28       0      8       1       0
4      Diego     Maradona   68       4      5       6       1
5  Cristiano      Ronaldo   34       0     10       0       0
6     Mihail          Tal   58      15     10       0       0
7      Kathy        Bates   22      12      5       2       0
8     Nicole       Kidman   45       2      6       0       0
9        Ray      Milland   52      18      4       5       1

In [ ]:
lucancer = lucancer.drop('Surname', axis=1)
lucancer = lucancer.drop('Name', axis=1)
lucancer.head(5)

   Age  Smokes  AreaQ  Alkhol  Result
0   35       3      5       4       1
1   27      20      2       5       1
2   30       0      5       2       0
3   28       0      8       1       0
4   68       4      5       6       1

In [ ]:
X = lucancer.iloc[:,:4].head(10)
y = lucancer.iloc[:,4].head(10)
X

   Age  Smokes  AreaQ  Alkhol
0   35       3      5       4
1   27      20      2       5
2   30       0      5       2
3   28       0      8       1
4   68       4      5       6
5   34       0     10       0
6   58      15     10       0
7   22      12      5       2
8   45       2      6       0
9   52      18      4       5

In [ ]:

from sklearn import datasets
from sklearn.linear_model import Perceptron 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.25)

# scale du lieu

sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train) # scale X_train
X_test_std = sc.transform(X_test)   # scale X_test

model = Perceptron(max_iter = 600, eta0 = 0.6, random_state = 0)
# (so lan hoc, toc do hoc, ngau nhien=0)
model.fit(X_train_std, y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)
print("Do chinh xac mo hinh sau scale : ", accuracy_score(y_test, y_pred))

[0 0 0]
2    0
3    0
8    0
Name: Result, dtype: int64
Do chinh xac mo hinh sau scale :  1.0